# Generated by Django 3.2.9 on 2021-12-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=45)),
                ('device_type', models.CharField(max_length=45)),
                ('device_asset', models.CharField(max_length=45, unique=True)),
                ('device_serial', models.CharField(max_length=45, unique=True)),
                ('device_model', models.CharField(max_length=45)),
                ('device_location', models.CharField(max_length=45)),
                ('device_ip', models.CharField(max_length=45)),
                ('device_mac', models.CharField(max_length=45)),
                ('device_school', models.CharField(max_length=4)),
                ('device_notes', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'all_devices',
            },
        ),
    ]
